### ISSUE TITLE
6.0 not tagged @ hub.docker.com

### ISSUE THREAD

**Issue by macneib** [pcvolkmer/docker-jenkins-slave-nodejs#1]
Thanks for making this image
Wondering if you are going to tag the 6.0 @pcvolkmer hub.docker.com

**Comment by pcvolkmer** [comment]
Thanks for the report. Some kind of package install error occurred on automated build

```
[...] libatk1.0-data_2.14.0-1_all.deb Hash Sum mismatch
```

Triggered new build, 6.0 is available now.
